---
name: Reusable workflow to run integration tests with specific images
on:
  workflow_call:
    secrets:
      opensearch_aws_access_id:
        description: AWS access ID to use within the opensearch integration tests.
        required: true
      opensearch_aws_secret_key:
        description: AWS secret key to use within the opensearch integration tests.
        required: true
      opensearch_admin_password:
        description: Default admin password use within the opensearch integration tests.
        required: true
      terraform_api_token:
        description: Default terraform API token to use when running integration tests.
        required: true
    inputs:
      image_name:
        description: The image repository and name to use.
        required: false
        default: ghcr.io/fluent/fluent-bit/master
        type: string
      image_tag:
        description: The image tag to use.
        required: false
        default: x86_64
        type: string
jobs:

  call-run-integration-kind:
    name: Run integration tests on KIND
    # Can test for multiple K8S versions with KIND
    strategy:
      fail-fast: false
      matrix:
        k8s-release: [ 'v1.23.5', 'v1.22.7', 'v1.21.10' ]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Test image exists and cache locally
        run: docker pull ${{ inputs.image_name }}:${{ inputs.image_tag }}

      - uses: actions/checkout@v3
        with:
          repository: fluent/fluent-bit-ci
          path: ci

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: 'app.terraform.io'
          cli_config_credentials_token: ${{ secrets.terraform_api_token }}

      - name: Replace terraform variables.
        run: |
          sed -i -e "s|\$OPENSEARCH_AWS_ACCESS_ID|${{ secrets.opensearch_aws_access_id }}|g" default.auto.tfvars
          sed -i -e "s|\$OPENSEARCH_AWS_SECRET_KEY|${{ secrets.opensearch_aws_secret_key }}|g" default.auto.tfvars
          sed -i -e "s|\$OPENSEARCH_ADMIN_PASSWORD|${{ secrets.opensearch_admin_password }}|g" default.auto.tfvars
        working-directory: ci/terraform/
        shell: bash

      - name: Terraform init
        run: terraform init
        working-directory: ci/terraform/

      - name: Terraform validate
        run: terraform validate -no-color
        working-directory: ci/terraform/

      - name: Terraform plan
        run: terraform plan
        working-directory: ci/terraform/

      - name: Terraform apply
        if: ${{ github.event_name != 'pull_request' }}
        run: terraform apply -input=false -auto-approve
        working-directory: ci/terraform/

      - name: Get the AWS OpenSearch endpoint
        id: aws-opensearch-endpoint
        run: terraform output -no-color -raw aws-opensearch-endpoint
        working-directory: ci/terraform/

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.6.0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          node_image: kindest/node:${{ matrix.k8s-release }}
          cluster_name: kind

      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.8.1

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3.0

      - name: Run tests
        run:  |
          kind load docker-image ${{ inputs.image_name }}:${{ inputs.image_tag }}
          ./run-tests.sh
        shell: bash
        working-directory: ci/
        env:
          FLUENTBIT_IMAGE_REPOSITORY: ${{ inputs.image_name }}
          FLUENTBIT_IMAGE_TAG: ${{ inputs.image_tag }}
          HOSTED_OPENSEARCH_HOST: ${{ steps.aws-opensearch-endpoint.outputs.stdout }}
          HOSTED_OPENSEARCH_PORT: 443
          HOSTED_OPENSEARCH_USERNAME: admin
          HOSTED_OPENSEARCH_PASSWORD: ${{ secrets.opensearch_admin_password }}
