name: Sync with OSS Fluent Bit
on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync-with-fluent-bit:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3