name: CIFuzz
on:
  pull_request:
    # Only fuzz when C source files change
    paths:
      - '**.c'
      - '**.h'
jobs:
  fuzzing:
    name: PR - fuzzing test
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'fluent-bit'
        dry-run: false
        language: c
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'fluent-bit'
        fuzz-seconds: 600
        dry-run: false
        language: c
        output-sarif: true
    - name: Upload Crash
      uses: actions/upload-artifact@v5
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
    - name: Upload Sarif
      if: always() && steps.build.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v4
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: cifuzz-sarif/results.sarif
        checkout_path: cifuzz-sarif
        category: CIFuzz
