name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

jobs:

  hadolint-pr:
    runs-on: ubuntu-latest
    name: PR - Hadolint
    steps:
      - uses: actions/checkout@v2
        # Ignores do not work: https://github.com/reviewdog/action-hadolint/issues/35 is resolved
      - uses: reviewdog/action-hadolint@v1
        with:
          exclude: |
            packaging/testing/smoke/packages/Dockerfile.*

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: lib plugins tests

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  # Special lint to handle reusable workflows requiring an explicit branch.
  # We cannot just reference the current/default but have to make sure it is `master`.
  reusable-workflow_lint-pr:
    runs-on: ubuntu-latest
    name: PR - Reusable workflow linting
