name: PR - packaging tests run on-demand via label
on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    branches:
      - master

# Cancel any running on push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This job provides this metadata for the other jobs to use.
  pr-package-test-build-get-meta:
    # This is a long test to run so only on-demand for certain PRs
    if: contains(github.event.pull_request.labels.*.name, 'ok-package-test')
    name: Get metadata to add to build
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    permissions:
      contents: none
    steps:
      # For cron builds, i.e. nightly, we provide date and time as extra parameter to distinguish them.
      - name: Get current date
        id: date
        run: echo "date=$(date '+%Y-%m-%d-%H_%M_%S')" >> $GITHUB_OUTPUT

      - name: Debug event output
        uses: hmarr/debug-action@v3

  pr-container-builds:
    name: PR - container builds
    needs:
      - pr-package-test-build-get-meta
      - pr-package-test-build-generate-matrix
    uses: ./.github/workflows/call-build-images.yaml
    with:
      version: pr-${{ github.event.number }}
      ref: ${{ github.ref }}
      registry: ghcr.io
      username: ${{ github.actor }}
      image: ${{ github.repository }}/pr
      unstable: ${{ needs.pr-package-test-build-get-meta.outputs.date }}
      # We do not push as forks cannot get a token with the right permissions
      push: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      cosign_private_key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign_private_key_password: ${{ secrets.COSIGN_PASSWORD }}

  pr-package-test-build-generate-matrix:
    name: PR - packages build matrix
    needs:
      - pr-package-test-build-get-meta
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.set-matrix.outputs.build-matrix }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository, always latest for action
        uses: actions/checkout@v5

      # Set up the list of target to build so we can pass the JSON to the reusable job
      - uses: ./.github/actions/generate-package-build-matrix
        id: set-matrix
        with:
          ref: master

  pr-package-test-build-packages:
    name: PR - packages build Linux
    needs:
      - pr-package-test-build-get-meta
      - pr-package-test-build-generate-matrix
    uses: ./.github/workflows/call-build-linux-packages.yaml
    with:
      version: pr-${{ github.event.number }}
      ref: ${{ github.ref }}
      build_matrix: ${{ needs.pr-package-test-build-generate-matrix.outputs.build-matrix }}
      unstable: ${{ needs.pr-package-test-build-get-meta.outputs.date }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  pr-package-test-build-windows-package:
    name: PR - packages build Windows
    needs:
      - pr-package-test-build-get-meta
    uses: ./.github/workflows/call-build-windows.yaml
    with:
      version: pr-${{ github.event.number }}
      ref: ${{ github.ref }}
      unstable: ${{ needs.pr-package-test-build-get-meta.outputs.date }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  pr-package-test-build-macos-package:
    name: PR - packages build MacOS
    needs:
      - pr-package-test-build-get-meta
    uses: ./.github/workflows/call-build-macos.yaml
    with:
      version: pr-${{ github.event.number }}
      ref: ${{ github.ref }}
      unstable: ${{ needs.pr-package-test-build-get-meta.outputs.date }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
